#ifndef LABEXEIMAGING_GLOBAL_H
#define LABEXEIMAGING_GLOBAL_H

#include <QGlobal.h>

#ifdef LABEXEIMAGING_LIB
# define LABEXEIMAGING_EXPORT Q_DECL_EXPORT
#else
# define LABEXEIMAGING_EXPORT Q_DECL_IMPORT
#endif

#endif // LABEXEIMAGING_GLOBAL_H
