#ifndef LABEXESEQUENCER_GLOBAL_H
#define LABEXESEQUENCER_GLOBAL_H

#include <QGlobal.h>

#ifdef LABEXESEQUENCER_LIB
# define LABEXESEQUENCER_EXPORT Q_DECL_EXPORT
#else
# define LABEXESEQUENCER_EXPORT Q_DECL_IMPORT
#endif

#endif // LABEXESEQUENCER_GLOBAL_H
