#ifndef LABEXEOPTIMIZING_GLOBAL_H
#define LABEXEOPTIMIZING_GLOBAL_H

#include <QGlobal.h>

#ifdef LABEXEOPTIMIZING_LIB
# define LABEXEOPTIMIZING_EXPORT Q_DECL_EXPORT
#else
# define LABEXEOPTIMIZING_EXPORT Q_DECL_IMPORT
#endif

#endif // LABEXEOPTIMIZING_GLOBAL_H
